---
##
# Add entries to /etc/hosts
# PROBLEM with lineinfile does not add if not exists. stupid thing
##
#- name: LINEINFILE | Add entries to /etc/hosts
#  lineinfile:
#    state: present
#    path: /etc/hosts
#    line: "{{ item }}"
#  with_items: "{{ system_etc_hosts }}"

- name: LINEINFILE | Add entries to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    regexp: '{{ item.host }}'
    line: "{{ item.ip }}\t{{ item.host }}"
  with_items: "{{ system_etc_hosts }}"
