---
##
# Grub optimisation
##
- name: SHELL | Check grub elevator existence ( IGNORE THIS ERROR )
  shell: "grep GRUB_CMDLINE_LINUX {{ system_grub_defaults_file }} | grep -c elevator"
  register: grub_elevator_exists
  ignore_errors: true

- name: LINEINFILE | Set grub elevator
  lineinfile:
    path: "{{ system_grub_defaults_file }}"
    regexp: '^GRUB_CMDLINE_LINUX='
    line: "GRUB_CMDLINE_LINUX=\"elevator={{ system_grub_elevator_mode }}\""
  when: grub_elevator_exists.stdout == "0"

- name: SHELL | Update grub
  shell: update-grub2
  when: grub_elevator_exists.stdout == "0"

- name: SHELL | Reboot server if needed
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: grub_elevator_exists.stdout == "0"

- name: LOCAL_ACTION | Waiting for server to come back
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: grub_elevator_exists.stdout == "0"
