---
##
# System setup: Docker
##
- name: APT | Add the Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts['os_family']|lower }}/gpg
    state: present

- name: APT | Add the Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['os_family']|lower }} {{ ansible_distribution_release|lower }} stable
    state: present

- name: APT | Update apt repository cache and install the required docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: "{{ system_package_mode }}"
    update_cache: yes

- name: USER | Add existing user to docker group
  user:
    name: '{{ system_docker_user }}'
    groups: '{{ system_docker_group }}'
    append: yes
  when: system_docker_user