---
##
# System setup: basic packages
##
- name: APT | Installation for default system packages
  apt:
    name: "{{ system_packages }}"
    state: "{{ system_package_mode }}"
    update_cache: yes

- name: APT | Make sure python-pip is present
  apt:
    name: python-pip
    state: present

- name: APT | Make sure python-setuptools is present
  apt:
    name: python-setuptools
    state: present

- name: APT | Make sure python3-pip is present
  apt:
    name: python3-pip
    state: present

- name: APT | Make sure python3-setuptools is present
  apt:
    name: python3-setuptools
    state: present

- name: PIP | Make sure pymysql is present
  pip:
    name: pymysql
    state: present
